stages:
  data:
    cmd: python3 src/data.py
    deps:
      - src/data.py
    outs:
      - data/raw/iris.csv

  prepare:
    cmd: python3 src/prepare.py
    deps:
      - src/prepare.py
      - data/raw/iris.csv
    params:
      - prepare.test_size
      - prepare.random_state
    outs:
      - data/processed/X_train.npy
      - data/processed/X_test.npy
      - data/processed/y_train.npy
      - data/processed/y_test.npy

  train:
    cmd: python src/train.py
    deps:
      - src/train.py
      - data/processed/X_train.npy
      - data/processed/X_test.npy
      - data/processed/y_train.npy
      - data/processed/y_test.npy
    params:
      - train.model_type
    outs:
      - models/model.pkl
    metrics:
      - metrics/train_metrics.json
