prepare:
  test_size: 0.2
  random_state: 42

train:
  model_type: logistic_regression
  random_state: 42
  logistic_regression:
    max_iter: 100
    C: 1.0
  random_forest:
    n_estimators: 100
    max_depth: 5
